### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by nightclubs** [therealOri/Genter#15]
Very cool, but as a password generator, most of this is unnecessary because most websites only accept special characters and English alphabetical characters. I'd also like to point out that in your GitHub profile README, you misspelled "world" and wrote "wolrd," so sincerely zt / nightclubs.

**Comment by therealOri** [comment]
Thank you for the heads up! (typo has been fixed)

And I am aware of that fact..but I do know that there are websites out there that don't only use that format. I also wanted my generator to have a bit of fun variety. To be a bit more unique...instead of the same old same old. (literally "old") way of doing things.

It's also odd to me that a good portion of websites don't allow anything more than what you said.

**Comment by therealOri** [comment]
You may continue discussion and dialogue over in the [discussions](https://github.com/therealOri/Genter/discussions/1) area!
